🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🙆🏼‍♂️👩‍🦱🇵🇪👩🏾‍🎓

Full error log:
Error:  asset 2022-7-25--0-26-30--96e9966d-03a6-4266-a901-4a00cf98444f/main.min.js 136 KiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 120 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB
./node_modules/destroyable/dist/errors/CollisionError.js 1.3 KiB [built] [code generated]
./node_modules/destroyable/dist/errors/NotFoundError.js 1.29 KiB [built] [code generated]
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 54.7 KiB [built] [code generated]
./node_modules/xyzt/dist/main.js 26.4 KiB [built] [code generated]
modules by path ./src/ 7.49 KiB
./src/00-index.ts 135 bytes [built] [code generated]
./src/cube-art.tsx 2.2 KiB [built] [code generated]
./src/cube-tool-module.tsx 5.16 KiB [built] [code generated] [1 error]
./package.json 614 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\cube-drawing\src\cube-tool-module.tsx
./src/cube-tool-module.tsx 50:56-109
[tsl] ERROR in C:\Users\me\work\collboard\cube-drawing\src\cube-tool-module.tsx(50,57)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 4:0-29

webpack 5.35.1 compiled with 1 error in 10414 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\lib\Watching.js:201:28)