🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
👸🏽👨🏼‍🔬👏🏻🚴🏾

Full error log:
Error:  asset 2022-9-14--22-39-22--75f90c08-2dec-4bae-b76f-5a59def1b6d1/main.min.js 167 KiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 150 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB
./node_modules/destroyable/dist/errors/CollisionError.js 1.3 KiB [built] [code generated]
./node_modules/destroyable/dist/errors/NotFoundError.js 1.29 KiB [built] [code generated]
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 85.4 KiB [built] [code generated]
./node_modules/xyzt/dist/main.js 26.4 KiB [built] [code generated]
modules by path ./src/ 7.49 KiB
./src/00-index.ts 135 bytes [built] [code generated]
./src/cube-art.tsx 2.2 KiB [built] [code generated] [2 errors]
./src/cube-tool-module.tsx 5.17 KiB [built] [code generated]
./package.json 613 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\cube-drawing\src\cube-art.tsx
./src/cube-art.tsx 8:13-20
[tsl] ERROR in C:\Users\me\work\collboard\cube-drawing\src\cube-art.tsx(8,14)
TS2515: Non-abstract class 'CubeArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.
@ ./src/00-index.ts 3:0-21

ERROR in C:\Users\me\work\collboard\cube-drawing\src\cube-art.tsx
./src/cube-art.tsx 8:13-20
[tsl] ERROR in C:\Users\me\work\collboard\cube-drawing\src\cube-art.tsx(8,14)
TS2515: Non-abstract class 'CubeArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.
@ ./src/00-index.ts 3:0-21

webpack 5.35.1 compiled with 2 errors in 5956 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\cube-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\cube-drawing\node_modules\webpack\lib\Watching.js:201:28)